name: Validate Model

on:
  push:
    paths:
      - 'models/**'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        lfs: true   # Enable Git LFS

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Validation
      run: python scripts/compare_models.py --base base_model/model.pkl --new models/

    - name: Commit Base Model Update
      if: success()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git lfs track base_model/*.pkl
        git add base_model/
        if git diff --cached --quiet; then
          echo "No changes to base model"
        else
          git commit -m "Update base model after validation"
          git push
          echo "Base model updated and pushed"
        fi

    - name: Upload Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: validation-report
        path: validation_report.txt
