name: Validate Model

on:
  push:
    branches:
      - main  # Trigger on direct pushes to main for validation

permissions:
  contents: write  # Allow writing to repo for git push

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        lfs: true   # Enable Git LFS

    - name: Check if models changed
      id: changed-files
      run: |
        if git diff --name-only HEAD~1 | grep -q '^models/'; then
          echo "models_changed=true" >> $GITHUB_OUTPUT
        else
          echo "models_changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Set up Python
      if: steps.changed-files.outputs.models_changed == 'true'
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      if: steps.changed-files.outputs.models_changed == 'true'
      run: pip install -r requirements.txt

    - name: Run Validation
      if: steps.changed-files.outputs.models_changed == 'true'
      run: python scripts/compare_models.py --base base_model/model.pkl --new models/

    - name: Commit Base Model Update
      if: steps.changed-files.outputs.models_changed == 'true' && success()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git lfs track base_model/*.pkl
        git add base_model/
        if git diff --cached --quiet; then
          echo "No changes to base model"
        else
          git commit -m "Update base model after validation"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push
          echo "Base model updated and pushed"
        fi

    - name: Upload Logs
      if: steps.changed-files.outputs.models_changed == 'true' && always()
      uses: actions/upload-artifact@v4
      with:
        name: validation-report
        path: validation_report.txt
