name: Validate Model

on:
  push:  # Trigger on pushes to any branch (for feature branches)
  pull_request:
    branches:
      - main  # Trigger on PRs targeting main

permissions:
  contents: write  # Allow writing to repo for git push

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        lfs: true   # Enable Git LFS
        fetch-depth: 0  # Fetch all history to ensure proper diff comparison

    - name: Check if models changed
      id: changed-files
      run: |
        if git diff --name-only HEAD~1 | grep -q '^models/'; then
          echo "models_changed=true" >> $GITHUB_OUTPUT
        else
          echo "models_changed=false" >> $GITHUB_OUTPUT
          echo "No model changes detected. Skipping validation."
        fi

    - name: Set up Python
      if: steps.changed-files.outputs.models_changed == 'true'
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      if: steps.changed-files.outputs.models_changed == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install scikit-learn pandas numpy joblib

    - name: Fetch Current Model from Main Branch
      if: steps.changed-files.outputs.models_changed == 'true'
      run: |
        git fetch origin main
        mkdir -p current_model
        # Fetch the latest model from main's models/ folder
        MODEL_FILE=$(git ls-tree -r origin/main --name-only models/ | head -1)
        if [ -n "$MODEL_FILE" ]; then
          git show origin/main:$MODEL_FILE > current_model/current_model.pkl
          echo "Current model fetched from main"
        else
          echo "No model in main - will use placeholder"
          touch current_model/current_model.pkl
        fi

    - name: Run Validation
      if: steps.changed-files.outputs.models_changed == 'true'
      run: python scripts/compare_models.py --base current_model/current_model.pkl --new models/

    - name: Install GitHub CLI
      if: github.event_name == 'pull_request' && steps.changed-files.outputs.models_changed == 'true'
      run: |
        curl -Lo gh.tar.gz https://github.com/cli/cli/releases/latest/download/gh_2.40.1_linux_amd64.tar.gz
        tar -xzf gh.tar.gz
        sudo mv gh_2.40.1_linux_amd64/bin/gh /usr/local/bin/
        gh --version

    - name: Auto-Merge PR on Better Model
      if: github.event_name == 'pull_request' && steps.changed-files.outputs.models_changed == 'true' && success()
      run: |
        if grep -q "Base model will be updated" validation_report.txt; then
          echo "Auto-merging PR due to better model"
          gh pr merge ${{ github.event.pull_request.number }} --merge --delete-branch-when-merged=false
          echo "PR merged successfully"
        else
          echo "PR not merged - model not better than current in main"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Logs
      if: steps.changed-files.outputs.models_changed == 'true' && always()
      uses: actions/upload-artifact@v4
      with:
        name: validation-report
        path: validation_report.txt

