name: Validate Model

on:
  push:
    paths:
      - 'models/**'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        lfs: true   # Enable Git LFS

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Validation
      run: python scripts/compare_models.py --base base_model/model.pkl --new models/

    - name: Commit Base Model Update
      if: success()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add base_model/
        git commit -m "Update base model after validation" || echo "No changes to commit"
        git push
